# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: psegura- <psegura-@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/09/09 13:25:54 by psegura-          #+#    #+#              #
#    Updated: 2023/09/14 01:07:58 by psegura-         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM alpine:3.18.2

# # Label your image with your information
# LABEL maintainer="psegura-@student.42madrid.com"

# Install Nginx and any other required dependencies
RUN apk update ; apk upgrade ; apk add --no-cache nginx
# Instal vim, curl and OpenSSL
RUN apk add --no-cache vim
RUN apk add --no-cache curl

RUN mkdir -p /etc/nginx/ssl
RUN apk add --no-cache openssl

RUN openssl req -x509 -nodes -out /etc/nginx/ssl/inception.crt -keyout /etc/nginx/ssl/inception.key -subj "/C=FR/ST=IDF/L=Madrid/O=42/OU=42/CN=psegura-.42.fr/UID=login"

COPY conf/nginx.conf /etc/nginx/nginx.conf

RUN chmod 755 /var/www/html

RUN chown -R nginx:nginx /var/www/html

# CMD ["nginx", "-g", "daemon off;"]

# # Create a directory for Nginx to store its logs
# RUN mkdir -p /var/log/nginx

# # Expose the default HTTP port (80)
# EXPOSE 80

# # Start Nginx in the foreground when a container is launched
# CMD ["nginx", "-g", "daemon off;"]