version: '3'

services:

# Falta configurar nginx para que redirija las peticiones
# del puerto 80 al 443, y que redirija la respuesta
# del servidor al puerto 9000, para que wodrpress pueda mostrarlo

#########################__Nginx__#########################
  # nginx:
  #   build: nginx
  #   container_name: nginx

  #   ports:
  #     - "80:80"
  #     - "443:443"

  #   networks:
  #     - inception


########################__MariaDB__########################
  mariadb:
    build: mariadb
    container_name: mariadb

    env_file:
      - .env
    
    restart: always

    networks:
      - inception

    volumes:
      - db_volume:/var/lib/mysql


#######################__Wordpress__#######################
  wordpress:
    build: wordpress
    container_name: wordpress

    depends_on:
      - mariadb

    env_file:
      - .env
    
    networks:
      - inception

    volumes:
      - wp_volume:/var/www/html


########################__Volumes__########################
volumes:

  db_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/psegura-/Desktop/cursus/inception/incesto/volumes/database

  
  wp_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/psegura-/Desktop/cursus/inception/incesto/volumes/wordpress


########################__Network__########################
networks:
  inception:
    name: inception

