version: '3'

services:

# Falta configurar nginx para que redirija las peticiones
# del puerto 80 al 443, y que redirija la respuesta
# del servidor al puerto 9000, para que wodrpress pueda mostrarlo

  # nginx:
  #   build: nginx
  #   container_name: nginx

  #   ports:
  #     - "80:80"
    #   - "443:443"
  
  mariadb:
    build: mariadb
    container_name: mariadb

    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD:  ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:       ${MYSQL_DATABASE}
      MYSQL_USER:           ${MYSQL_USER}
      MYSQL_PASSWORD:       ${MYSQL_PASSWORD}
    
    restart: always

    volumes:
      - db_volume:/var/lib/mysql/

  # wordpress:
  #   build: wordpress
  #   container_name: wordpress

  #   depends_on:
  #     - mariadb

  #   env_file:
  #     - .env
  #   environment:
  #     WORDPRESS_DB_HOST:      ${WORDPRESS_DB_HOST}
  #     WORDPRESS_DB_NAME:      ${WORDPRESS_DB_NAME}
  #     WORDPRESS_DB_USER:      ${WORDPRESS_DB_USER}
  #     WORDPRESS_DB_PASSWORD:  ${WORDPRESS_DB_PASSWORD}
  #     WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
    
    # volumes:
    #  - db_volume:/volume

volumes:

  db_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/psegura-/Desktop/cursus/inception/incesto/volumes/database

  
  # wp_volume:
  #   driver: local
  #   driver_opts:
  #     o: bind
  #     type: none
  #     device: /Users/psegura-/Desktop/cursus/inception/incesto/volumes/wordpress
